### ISSUE TITLE
Result header is showing the breadcrumb instead of the page title

### ISSUE THREAD

**Issue by lucky13820** [searx/searx#1981]
I'm running the latest version of searX. The result header will show the breadcrumb of the page, instead of the page title. This only happens to the Google result. StartPage works fine.
![CleanShot 2020-06-01 at 14 03 07](https://user-images.githubusercontent.com/7293811/83454790-9508c280-a411-11ea-8600-befd3354f52e.jpg)

**Comment by travnewmatic** [comment]
same on mine 0.16.0-157-19e32dc6
![2020-06-02-131304](https://user-images.githubusercontent.com/11083305/83482432-dca35300-a4d2-11ea-8692-356e52b73a22.png)

**Comment by travnewmatic** [comment]
similar on searx.be 0.16.0
![2020-06-02-131555](https://user-images.githubusercontent.com/11083305/83482612-415ead80-a4d3-11ea-9cd7-41ea245b2212.png)

**Comment by lucky13820** [comment]
Yeah, I guess Google changed something again.

**Comment by travnewmatic** [comment]
using the latest version, the problem appears to go away if google search is disabled

**Comment by return42** [comment]
Thanks for pointing out .. I am working on a patch for this issue. I will contact you again when the PR is ready to merge.

**Comment by travnewmatic** [comment]
> Thanks for pointing out .. I am working on a patch for this issue. I will contact you again when the PR is ready to merge.

very welcome!  thanks for all the hard work on this project.  searx is one of my most-used self-hosted web applications.

**Comment by BBaoVanC** [comment]
Huh, this wasn't happening for me before, but now it's happening (since yesterday) on both Google and Startpage. I'll have to try the linked PR.

**Comment by return42** [comment]
> 'll have to try the linked PR.

Don't do it, the PR #1985 is obsolete, google engines has been fixed since. Use a fresh clone from master, should fix the bug.

**Comment by BBaoVanC** [comment]
I'm already fully up to date. My fork is at https://git.bbaovanc.com/bbaovanc/searx if you
want to take a look it.

**Comment by return42** [comment]
> but now it's happening (since yesterday) on both Google and Startpage
>  My fork is at https://git.bbaovanc.com/bbaovanc/searx 

Made a clone of your repo and tested local: no breadcrumbs, everything is fine. Google & Startpage

In the public instance: https://searx.bbaovanc.com/searx/search?q=%21google%20foo&categories=none&language=en-US

Google & Startpage do not have any results ..

**Comment by BBaoVanC** [comment]
> > but now it's happening (since yesterday) on both Google and Startpage
> > My fork is at https://git.bbaovanc.com/bbaovanc/searx
> 
> Made a clone of your repo and tested local: no breadcrumbs, everything is fine. Google & Startpage
> 
> In the public instance: https://searx.bbaovanc.com/searx/search?q=%21google%20foo&categories=none&language=en-US
> 
> Google & Startpage do not have any results ..

I had hidden startpage after the issue, and I just re-enabled it and it's still having the issue (on results that didn't come from other engines, only startpage).

![Image](https://img.bbaovanc.com/ma72trdp.png)

**Comment by BBaoVanC** [comment]
On my local computer, Google works fine, but Startpage is broken. (My public instance is blocked by Google so I can't test that)

**Comment by BBaoVanC** [comment]
Aha -- #2395 is exactly my issue.

**Comment by dalf** [comment]
The initial issue is fixed.
