### ISSUE TITLE
https-scheme missing in preferences-page 

### ISSUE THREAD

**Issue by avpnusr** [searx/searx#2740]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
Master-Branch on commit: 547478089f1a48bb22a7651435db6cf941afc2f5

**How did you install Searx?**
Deployed via searx-docker

**What happened?**
I built the last docker-image for searx on April 1st, I think after commit c0668d248e0ba900e12c6ee07ef27b03d8b9b0f6 
Today I built the docker-image with the newest version, after fixing the "trailing /"-issue everythin seems to work quite fine, but when entering the "preferences" on my instance, the link on the end of the page just displays as "http://searx.mydomain.tld", so it's missing the "https://...". Clicking "save" just brings up a white page with my "http://searx.mydomain.tld" written in the body and nothing else.

Seems like one of the last commits, had a negative impact on the "https://"-scheme in this particular field, the rest seems to work fine.

**How To Reproduce**
Build image from commit c0668d248e0ba900e12c6ee07ef27b03d8b9b0f6 and with the latest commit, then go to preferences and have a look at the link at the end of the preferences-page. Then make some settings and try to save.

**Expected behavior**
"https"-scheme of base-url should be passed in preferences and saving the settings in the preferences-page should not result in an empty page.

**Comment by dalf** [comment]
confirmed.

@asciimoo @kvch @unixfox I suggest a rollback of https://github.com/searx/searx/pull/2656

**Comment by return42** [comment]
From my side, it is OK if we rollback .. if we give #2656 a second try in which we test the docker images (I'm not familiar with docker and can't say what the problem is / but this can be discussed later).

update:

Does it help to partial rollback this section

https://github.com/searx/searx/pull/2656/files#diff-ab9553a5df12bab91ccac7a4b9af78fbd160e35bffae9a340bf75ed736d50a07L812-L817

Could deleting the `redirect(..)` be the cause for this issue?

**Comment by BBaoVanC** [comment]
> From my side, it is OK if we rollback .. if we give #2656 a second try in which we test the docker images (I'm not familiar with docker and can't say what the problem is / but this can be discussed later).
> 
> update:
> 
> Does it help to partial rollback this section
> 
> https://github.com/searx/searx/pull/2656/files#diff-ab9553a5df12bab91ccac7a4b9af78fbd160e35bffae9a340bf75ed736d50a07L812-L817
> 
> Could deleting the `redirect(..)` be the cause for this issue?

Do you mean like this?

```diff
diff --git a/searx/webapp.py b/searx/webapp.py
index e20295b2..8fca385d 100755
--- a/searx/webapp.py
+++ b/searx/webapp.py
@@ -822,7 +822,7 @@ def preferences():

     # save preferences
     if request.method == 'POST':
-        resp = make_response(url_for('index', _external=True))
+        resp = make_response(redirect(url_for('index', _external=True)))
         try:
             request.preferences.parse_form(request.form)
         except ValidationException:
```

If so, it doesn't seem to work.

I tried reverting #2656 like dalf mentioned and it works.

**Comment by return42** [comment]
> not result in an empty page.

This issue is fixed in #2760 / the redirect was missing (in webapp.py)

> "https"-scheme of base-url should be passed in preferences 

~I am still unsure, but ATM I guess this related to the docker build (HTTP setup?) / I'm not an docker expert .. but I will give it a try.~

update: there is an base_url issue in the HTML templates / I will fix it.

**Comment by return42** [comment]
> "https"-scheme of base-url should be passed in preferences

this should now also be fixed in PR #2760 

@BBaoVanC @avpnusr @dalf could you approve, if PR #2760 fixes the issues we have with #2656 .. I can't test with docker behind HTTPS redirect, but I hope it will now work. Thanks a lot for you support.

**Comment by avpnusr** [comment]
Hey @return42 

first - thanks a lot for your effort :)
I will start a test-build with docker and try it right away

**Comment by avpnusr** [comment]
Okay, #2760 fixed the issue, that the "save"-button just shows the white page.
It brings me back to the front-page and the preferences are saved, as far as I can check.

What remains, ist the "wrong url" being displayed on the bottom of the preferences-page.
![grafik](https://user-images.githubusercontent.com/43516996/114419348-a2571780-9bb3-11eb-9f95-80d9bd04f60b.png)

The "http://" should be "https://" - as i click the save button, I can trace, that the "http://" URL is called, so it's not only the wrong text displayed. Works in my case, as I redirect HTTP -> HTTPS, but could lead to issues in other configurations.

**Comment by return42** [comment]
@avpnusr thanks a lot for your feedback!

One question I have, if you do a search query, is the https scheme in the link box correct?

![image](https://user-images.githubusercontent.com/554536/114420944-505ac580-9ba4-11eb-9df4-5ffccf203e95.png)

**Comment by avpnusr** [comment]
No, sorry it's also the http-scheme there:
![grafik](https://user-images.githubusercontent.com/43516996/114421339-80f72b00-9bb5-11eb-9d28-242d9060ada6.png)

Edit:
I never noticed it - but this is even the case in the build, that is from 01.04.2021! The link in the preferences is with the corret https-scheme, but the link on the search-query page is also http-scheme

**Comment by return42** [comment]
Ah, Ok .. thanks .. then I think #2656 is no longer responsible for (but I'm still unsure) .. I can only suppose it might be related to subdomain configuration or the base_url in settings.yml 

Did you set the `base_url` correct?

Edit:

> but the link on the search-query page is also http-scheme

:-) this was the reason I implemented PR  #2656 .. see discussion  https://github.com/searx/searx/discussions/2639

**Comment by avpnusr** [comment]
sorry, I missed that PR / discussion ;)

base_url is set correct and is also correctly exported to the container.
I will try to find out from which PR, the error existed.

What commit / version is your instance based on? 
You still have the "white page on preference save" issue, but the search-query link-box and the preferences-page both show the https scheme - so whatever commit that was, the scheme was still right there :)

**Comment by return42** [comment]
> What commit / version is your instance based on? You still have the "white page on preference save" issue, ..

I have just updated right now.  ATM my instance is at searx's master, plus a small branding, plus some fixes on top.  It includes this PR, for details have a look at the log of my branch at https://github.com/return42/searx/commits/master

But this instance is not identical to what you have.  I have used the [installation scripts](https://searx.github.io/searx/admin/installation.html#installation-scripts) and my HTTPS proxy is an [Apache Reverse Proxy](https://searx.github.io/searx/admin/installation-apache.html#installation-apache) (filtron).

**Comment by Zackptg5** [comment]
> > "https"-scheme of base-url should be passed in preferences
> 
> this should now also be fixed in PR #2760
> 
> @BBaoVanC @avpnusr @dalf could you approve, if PR #2760 fixes the issues we have with #2656 .. I can't test with docker behind HTTPS redirect, but I hope it will now work. Thanks a lot for you support.

Whew, thought I messed up something with nginx setup. This fixed the save issue for me :)
I'm on master branch btw. Strangely enough, url showed up correctly for me all along, it was just the redirect (I use https too)
