### ISSUE TITLE
0.10.0 - search page not found

### ISSUE THREAD

**Issue by nevtag** [searx/searx#686]
If I call searx, the page was loaded, but the search page not loaded.

![searx-page-not-found](https://cloud.githubusercontent.com/assets/1618658/18310937/cb9fac66-7501-11e6-97a0-a47addec60e3.png)

If I call it nativ, as shown in the install manual,
      python searx/webapp.py
      links2 http://localhost:8888
 it works.

Configuration is manual like, with uwsgi and apache.

Apache log:
"GET /static/css/bootstrap.min.css HTTP/1.0" 304 185
"GET /static/js/jquery-1.11.1.min.js HTTP/1.0" 304 183
"GET /static/themes/oscar/css/leaflet.min.css HTTP/1.0" 304 183
"GET /static/themes/oscar/css/logicodev.min.css HTTP/1.0" 304 183
"GET /static/js/bootstrap.min.js HTTP/1.0" 304 184
"GET /static/js/require-2.1.15.min.js HTTP/1.0" 304 183
"GET /static/themes/oscar/js/searx.min.js HTTP/1.0" 304 183
"GET /static/plugins/js/search_on_category_select.js HTTP/1.0" 304 182
"GET /static/themes/oscar/img/favicon.png HTTP/1.0" 200 2326
"GET /opensearch.xml HTTP/1.0" 200 366
"GET / HTTP/1.0" 404 4218

**Comment by dalf** [comment]
Can you copy / paste your Apache configuration?

**Comment by nevtag** [comment]
```
<VirtualHost *:80>
ServerName searx.xxxx.de

<Location />
    Options FollowSymLinks Indexes
    SetHandler uwsgi-handler
    uWSGISocket /run/uwsgi/app/searx/socket
    Order deny,allow
    Deny from all
    Allow from ipservice-xxx.pools.vodafone-ip.de 
</Location>

ErrorLog /var/log/apache2/searx_de_error.log
LogLevel emerg
TransferLog /var/log/apache2/searx_de_access.log
</VirtualHost>
```

Well, I have tested it, with proxypass to localhost:8888 and start searx from hand, and that works.
So I think it must be a configuration problem with apache or uwsgi

**Comment by Grotax** [comment]
I have the same problem followed this tutorial https://asciimoo.github.io/searx/dev/install/installation.html 
Found nothing in the apache2 log or the uwsgi/searx log also did enable debug mode in searx to get more infos but no errors. 
Also note that "preferences" and "about" work.

```

<IfModule mod_ssl.c>
        <VirtualHost *:443>
                ServerAdmin ...
                ServerName ...

                ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined

                SSLEngine on

                SSLCertificateFile ...     
                SSLCertificateKeyFile ...
                SSLCertificateChainFile ...

                <Location />
                    Options FollowSymLinks Indexes
                    SetHandler uwsgi-handler
                    uWSGISocket /run/uwsgi/app/searx/socket
                </Location>
        </VirtualHost>
</IfModule>
```

```
[uwsgi]
# Who will run the code
uid = searx
gid = searx

# disable logging for privacy
disable-logging = false

# Number of workers (usually CPU count)
workers = 2

# The right granted on the created socket
chmod-socket = 666

# Plugin to use and interpretor config
single-interpreter = true
master = true
plugin = python

# Module to import
module = searx.webapp

# Virtualenv and python path
virtualenv = /usr/local/searx/searx-ve/
pythonpath = /usr/local/searx/
chdir = /usr/local/searx/searx/
```

Running it via `python searx/webapp.py` on my private ip did work for me.

**Comment by nevtag** [comment]
If I call searx.domain.com/search it is working.

**Comment by ghost** [comment]
Same here - can confirm all findings with similar config:
- / not working
- /search gives search page, results post back to / which gives error again
- about and prefs working
- direct access works (http://localhost:8888/)

**Comment by nevtag** [comment]
The problem is solved with apache mod_uwsgi_proxy.
searx.ini

```
[uwsgi]
socket = 127.0.0.1:8080

# Who will run the code
uid = searx
gid = searx

# disable logging for privacy
disable-logging = true 

# Number of workers (usually CPU count)
workers = 1

# The right granted on the created socket
chmod-socket = 666

# Plugin to use and interpretor config
single-interpreter = true
master = true
plugin = python

# Module to import
module = searx.webapp

# Virtualenv and python path
virtualenv = /usr/local/searx/searx-ve/
pythonpath = /usr/local/searx/
chdir = /usr/local/searx/searx/

```

apache searx.conf

```
    ProxyPreserveHost On
    ProxyRequests Off
    ProxyPass / uwsgi://localhost:8080/
    ProxyPassReverse /  uwsgi://localhost:8080/

```

**Comment by ghost** [comment]
Working for me with mod_uwsgi_proxy - thanks!

**Comment by Grotax** [comment]
Changed my config. Now using mod_uwsgi_proxy, works.
Hint package name in Ubuntu: libapache2-mod-proxy-uwsgi

Thanks :)

**Comment by MrPetovan** [comment]
@asciimoo I still have this issue. I don't want to open any more port than I need, and the socket `/run/uwsgi/app/searx/socket` is correctly created by uwsgi. I followed the Installation page to the letter, the check passed and I didn't run `python searx/webapp.py` again after exiting the virtualenv bash.

Specs:
- Debian Jessie
- OpenSSL 1.0.1t, getting the Warning shown in #688 
- Apache 2.4.10

Config uwsgi:

```
[uwsgi]
# Who will run the code
uid = searx
gid = searx

# disable logging for privacy
disable-logging = true

# Number of workers (usually CPU count)
workers = 4

# The right granted on the created socket
chmod-socket = 666

# Plugin to use and interpretor config
single-interpreter = true
master = true
plugin = python

# Module to import
module = searx.webapp

# Virtualenv and python path
virtualenv = /usr/local/searx/searx-ve/
pythonpath = /usr/local/searx/
chdir = /usr/local/searx/searx/
```

Config Apache:

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
  ServerName searx.example.com

  <Location />
    Options FollowSymLinks Indexes
    SetHandler uwsgi-handler
    uWSGISocket /run/uwsgi/app/searx/socket
  </Location>

  #CustomLog /dev/null combined

  SSLCertificateFile /etc/letsencrypt/live/searx.example.com/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/searx.example.com/privkey.pem

  Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>

```

Log uswgi:

```
Fri Nov 11 06:06:09 2016 - *** Starting uWSGI 2.0.7-debian (64bit) on [Fri Nov 11 06:06:09 2016] ***
Fri Nov 11 06:06:09 2016 - compiled with version: 4.9.1 on 25 October 2014 19:17:54
Fri Nov 11 06:06:09 2016 - os: Linux-3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09)
Fri Nov 11 06:06:09 2016 - nodename: example.com
Fri Nov 11 06:06:09 2016 - machine: x86_64
Fri Nov 11 06:06:09 2016 - clock source: unix
Fri Nov 11 06:06:09 2016 - pcre jit disabled
Fri Nov 11 06:06:09 2016 - detected number of CPU cores: 8
Fri Nov 11 06:06:09 2016 - current working directory: /
Fri Nov 11 06:06:09 2016 - writing pidfile to /run/uwsgi/app/searx/pid
Fri Nov 11 06:06:09 2016 - detected binary path: /usr/bin/uwsgi-core
Fri Nov 11 06:06:09 2016 - setgid() to 1020
Fri Nov 11 06:06:09 2016 - setuid() to 1020
Fri Nov 11 06:06:09 2016 - your processes number limit is 31903
Fri Nov 11 06:06:09 2016 - your memory page size is 4096 bytes
Fri Nov 11 06:06:09 2016 - detected max file descriptor number: 1024
Fri Nov 11 06:06:09 2016 - lock engine: pthread robust mutexes
Fri Nov 11 06:06:09 2016 - thunder lock: disabled (you can enable it with --thunder-lock)
Fri Nov 11 06:06:09 2016 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/searx/socket fd 3
Fri Nov 11 06:06:09 2016 - Python version: 2.7.9 (default, Jun 29 2016, 13:11:10)  [GCC 4.9.2]
Fri Nov 11 06:06:09 2016 - Set PythonHome to /usr/local/searx/searx-ve/
Fri Nov 11 06:06:09 2016 - *** Python threads support is disabled. You can enable it with --enable-threads ***
Fri Nov 11 06:06:09 2016 - Python main interpreter initialized at 0x24009f0
Fri Nov 11 06:06:09 2016 - your server socket listen backlog is limited to 100 connections
Fri Nov 11 06:06:09 2016 - your mercy for graceful operations on workers is 60 seconds
Fri Nov 11 06:06:09 2016 - mapped 363840 bytes (355 KB) for 4 cores
Fri Nov 11 06:06:09 2016 - *** Operational MODE: preforking ***
Fri Nov 11 06:06:09 2016 - added /usr/local/searx/ to pythonpath.
WARNING:searx:You are using an old openssl version(OpenSSL 1.0.1t  3 May 2016), please upgrade above 1.0.2!
Fri Nov 11 06:06:12 2016 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x24009f0 pid: 30844 (default app)
Fri Nov 11 06:06:12 2016 - spawned uWSGI master process (pid: 30844)
Fri Nov 11 06:06:12 2016 - spawned uWSGI worker 1 (pid: 30877, cores: 1)
Fri Nov 11 06:06:12 2016 - spawned uWSGI worker 2 (pid: 30878, cores: 1)
Fri Nov 11 06:06:12 2016 - spawned uWSGI worker 3 (pid: 30879, cores: 1)
Fri Nov 11 06:06:12 2016 - spawned uWSGI worker 4 (pid: 30880, cores: 1)
```

Thanks in advance of any help.

Edit: More details: the `search/settings.yml` references a localhost:8888 server but nothing is listening on it.

`settings.yml` 

```
server:
    port : 8888
    bind_address : "127.0.0.1" # address to listen on
    secret_key : "[actual secret]" # change this!
    base_url : False # Set custom base_url. Possible values: False or "https://your.custom.host/location/"
    image_proxy : False # Proxying image results through searx
```

I thought `uwsgi` was taking care of that?

**Comment by asciimoo** [comment]
@Hypolite `port` and `bind_address` in `settings.yml` is used only if you run it without uwsgi (`python searx/webapp.py`).

**Comment by MrPetovan** [comment]
@asciimoo Thanks for the prompt response, others have circumvented the issue by manually running the Python app listening to the provided port, but I'd rather not do that. Do you have any clue/debug hints to fix this `/` page issue? I'm sorry I don't have any Python background to debug it myself.

I'd love to have a functional searx node without having to resort to tricks.

**Comment by MrPetovan** [comment]
For anyone else wondering, the package `libapache2-mod-proxy-uwsgi` doesn't work with Unix sockets until version `2.0.11`. However, the Debian Jessie package still is in version `2.0.7` despite the fact that the Apache2 package is more recent and allows Unix sockets in `ProxyPass` directives.

**Comment by vedranmiletic** [comment]
I can confirm same issue on Apache 2.4.25 on Debian 9. Doesn't happen on Nginx with Debian 9. I'm using the same configuration as [the installation docs](https://asciimoo.github.io/searx/dev/install/installation.html).

**Comment by vedranmiletic** [comment]
I got it working with mod_proxy_uwsgi as suggested above, I'll provide a patch for the docs.

**Comment by valodiadeseynes** [comment]
I'm technically still having this issue with version 0.12.0 on Debian 9 (with apache2). However, I've found a solution by changing searx's location with apache from / to /searx and it works.

Here is an excerpt from my apache config:

                RewriteEngine on
                RewriteRule   "^/$"  "/searx/"  [R]
                <Location /searx>
                    Options FollowSymLinks Indexes
                    SetHandler uwsgi-handler
                    uWSGISocket /run/uwsgi/app/searx/socket
                </Location>

The other solutions in this thread didn't work for me but this one does. Just throwing it out there in case somebody else is in my situation.

**Comment by MrPetovan** [comment]
I just tried to reinstall searx 0.12.0 from the installation docs and everything went well. Not sure what I did wrong the first time.

**Comment by Vertux** [comment]
This issue still persists with v0.14.0 (I just did a fresh install on a Ubuntu 16.04 server), the libapache2-mod-proxy-uwsgi solution, does not solve the problem for me. It would be nice if you could take a closer look into this issue @asciimoo 

@valodiadeseynes modification solves the issue but leads into another problem, which I have mentioned [here](https://github.com/asciimoo/searx/issues/760#issuecomment-370220343), at that time I did nit know that the rewrite rule triggers the issue.

@MrPetovan I really would like to know why the issue disappeared suddenly - I did the installation twice and followed exactly the installation docs like you, but it still does not work. I have no idea what to do.

**Comment by MrPetovan** [comment]
@Vertux I’m sorry, I kept getting timeouts while retrieving results, so I removed searx entirely from my system.

**Comment by Pofilo** [comment]
@Vertux what procedure did you use to install Searx ?
Just installed again according to the [documentation](https://asciimoo.github.io/searx/dev/install/installation.html) and it works fine (v0.14.0).

Let's try to understand and fix the problem !

To figure out if it is an apache misconfiguration, can you try to access [http://localhost:8888](http://localhost:8888) (or what you configured in `setting.yml`) directly on your server ?
If you only have access to the console (no desktop interface), you can install elinks (_apt-get install elinks_) and type _elinks_ in your terminal and then the url.
_[Wikipedia page about elinks](https://en.wikipedia.org/wiki/ELinks)_.

You should get something like that:
![searx_elinks](https://user-images.githubusercontent.com/7527594/41218932-1996d3cc-6d5d-11e8-8f00-bfdddad1163c.PNG)

If it doesn't work, you'll get something like that:
![searx_elinks_404](https://user-images.githubusercontent.com/7527594/41218944-244cd820-6d5d-11e8-843d-089e6f38ac6a.PNG)

If it works, can you give us your apache configuration ? (be careful to not reveal something private in it)

**Comment by Vertux** [comment]
@Pofilo thank you for the response.
I did the "classic" installation with Git with default values. If I start searx on the console (without uwsgi), the access with links/curl works fine, no problem. But when Apache and uwsgi comes into play and I access the subdomain I get the "Page not found" @nevtag already mentioned. If I add "/search/" to the subdomain name I get the right search page, which works fine.
At the moment I have shut down my public searx instance. Just for information it is a V-Root-Server with Plesk running Ubuntu 16.04. It is really a weird behavior - although it is a pretty "simple" installation. 

I just got the idea, that ModSecurity could be the reason for these issues - I have to check this, if I have a little more time.

Appendix: I did another test installation in a VM (Ubuntu 16.04) on a local server with Nignx, which runs perfectly fine.

**Comment by matzZz** [comment]
Put ‚DirectoryIndex disabled‘ in .htaccess.
Works for me.

**Comment by joshp23** [comment]
Running searx 14 on ubuntu 16.04 with apache2, same errors and behavior: 
-  when attempting to use wsgi according to the docs [here](https://asciimoo.github.io/searx/dev/install/installation.html#with-apache) I get a "file not found" error. 
-  when running manually with `python searx/webapp.py` and using mod_proxy in apache, it works.
-  using the `libapache2-mod-proxy-uwsgi` solution provided by @nevtag works.

It would be great if this were in the docs ;)

**Comment by xinomilo** [comment]
just came uppon this while moving from nginx to an apache2 server....  
what worked for me, was just adding 
`RewriteEngine on`
just before 
`<Location / >`
Everything else was exactly according to instructions. no extra ports or proxies. apache2+uwsgi just like with nginx. 

if someone can doublecheck/confirm this, then an update on docs would solve this for others as well, as it seems a common issue for apache users.

**Comment by xinomilo** [comment]
but because i needed some web headers, without me messing searx installation (https://github.com/asciimoo/searx/issues/715#issuecomment-257976755) , i went to reverse proxying solution with apache proxy_uwsgi module according to this : https://github.com/asciimoo/searx/issues/686#issuecomment-245639501

**Comment by juppin** [comment]
For me it works if i add "DirectoryIndex disabled" to the location block as @matzZz  mentioned for his htaccess file.
```
        <Location />
          DirectoryIndex disabled
          Options FollowSymLinks Indexes
          SetHandler uwsgi-handler
          uWSGISocket /run/uwsgi/app/searx/socket
        </Location>
```

Please test this fix and update doc if it works for everyone.
I think this will be the cleanest solution!

**Comment by ghost** [comment]
Had the same problem with following the the 0.15 tutorial. Thanks everyone for the helpful hints here, `DirectoryIndex disabled` finally solved my issue. 👍

**Comment by ghost** [comment]
Had the same problem with following the the 0.15 tutorial. Thanks everyone for the helpful hints here, DirectoryIndex disabled finally solved my issue.

**Comment by ashudubey007** [comment]
@asciimoo , even though this issue is closed, Could you please consider adding the "DirectoryIndex disabled" in the apache installation as below:

Current apache2 setting from the installation guide ([https://asciimoo.github.io/searx/dev/install/installation.html#basic-installation]
```
<Location />
    Options FollowSymLinks Indexes
    SetHandler uwsgi-handler
    uWSGISocket /run/uwsgi/app/searx/socket
</Location>

```
Recommended setting :
 
```
<Location />
    DirectoryIndex disabled 
    Options FollowSymLinks Indexes
    SetHandler uwsgi-handler
    uWSGISocket /run/uwsgi/app/searx/socket
</Location>

```
I'm requesting this because during setting up a searx website yesterday, we also faced exact same problem (on a fresh GCP f1-micro instance running Debian GNU/Linux 9 (stretch) ). Thankfully, the people who commented on this thread saved us tons of debugging efforts! :-)

I'm not an Apache expert, so I don't know the significance or side-effects of the above suggested change. In case this recommended change from so many people conflicts with something else in searx, or if it can create some loophole etc., then maybe it'll be to put this out as a note similar to what you perfectly did for disabling apache logs in the installation guide with a WARNING qualifier. 

My special thanks to all the people who spent their time to debug->find solution->post it here->verify/confirm that it worked for them!! :-)
